dist: xenial
sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
    - ./node_modules

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  - npm run test:coverage
  - ng build --prod --base-href https://lcpereira.github.io/marvel-catalog/ --deploy-url https://lcpereira.github.io/marvel-catalog/
  - mv dist/marvel-catalog/index.html dist/marvel-catalog/404.html

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/marvel-catalog
  on:
    branch: main
